import Navbar from "@/components/Navbar/Navbar";
import "./globals.css";
import Header from "@/components/Header/Header";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" data-theme="bumblebee" className="bg-white">
      <Header />
      <body className="">{children}</body>
    </html>
  );
}
